# Generated by Django 4.1.3 on 2022-11-13 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalapp', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_by', models.IntegerField()),
                ('like_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalapp.post')),
            ],
        ),
    ]
