# Generated by Django 4.1.3 on 2022-11-13 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalapp', '0003_postlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlike',
            name='like_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_like', to='personalapp.post'),
        ),
    ]
